// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:y
///
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCsbJrErITnGpjyjGoyc9CVCkQwVbtOXQ',
    appId: '1:262684968346:web:ae974f41eab37b35bae623',
    messagingSenderId: '262684968346',
    projectId: 'birthday-for-a-cause-15940',
    authDomain: 'birthday-for-a-cause-15940.firebaseapp.com',
    storageBucket: 'birthday-for-a-cause-15940.firebasestorage.app',
    measurementId: 'G-HDM29J4603',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNvX03qMZmYtCM2bNi7xY4I7SqE1TgNdc',
    appId: '1:262684968346:android:3216a7d53df996c0bae623',
    messagingSenderId: '262684968346',
    projectId: 'birthday-for-a-cause-15940',
    storageBucket: 'birthday-for-a-cause-15940.firebasestorage.app',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtbZTBU5fHrSaL5f1tIgZj3gwzzioWDag',
    appId: '1:262684968346:ios:1a5419128a6f363fbae623',
    messagingSenderId: '262684968346',
    projectId: 'birthday-for-a-cause-15940',
    storageBucket: 'birthday-for-a-cause-15940.firebasestorage.app',
    iosBundleId: 'com.example.paranubhutifoundation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCsbJrErITnGpjyjGoyc9CVCkQwVbtOXQ',
    appId: '1:262684968346:web:d9d42406b0efaa15bae623',
    messagingSenderId: '262684968346',
    projectId: 'birthday-for-a-cause-15940',
    authDomain: 'birthday-for-a-cause-15940.firebaseapp.com',
    storageBucket: 'birthday-for-a-cause-15940.firebasestorage.app',
    measurementId: 'G-P97L0CTWNC',
  );
}
